### ISSUE TITLE
Select element

### ISSUE THREAD

**Issue by Wingysam** [jloh/bulma-prefers-dark#17]
Could the select element be styled like button please? Currently I have to use custom CSS.

**Comment by jloh** [comment]
You mean this https://bulma.io/documentation/form/select/ ?

**Comment by Wingysam** [comment]
Yes. This is the CSS I use:
```css
  .select > select {
    border-color: #363636 !important;
    background-color: #0a0a0a !important;
    color: #dbdbdb !important;
  }
```
